version: '3.8'
services:
  app:
    image: ximple-challenge-app:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
    depends_on:
      - db
  db:
    image: oscarfonts/h2
    ports:
      - 1521:1521
      - 81:81
volumes:
  h2_data: